### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by Amyi12138** [RanQiwu/website#1]
![image](https://user-images.githubusercontent.com/54617008/63832041-90a30b00-c9a2-11e9-9b7a-196537e686c3.png)
![image](https://user-images.githubusercontent.com/54617008/63832310-1de65f80-c9a3-11e9-8b52-d5c1ee246727.png)
![image](https://user-images.githubusercontent.com/54617008/63833127-d82a9680-c9a4-11e9-8f12-fabbc765f98c.png)
![image](https://user-images.githubusercontent.com/54617008/63833290-3eafb480-c9a5-11e9-8d7c-273582dd3396.png)

**Comment by RanQiwu** [comment]
这些logo的尺寸的确不好看，稍后再优化一下。

**Comment by Amyi12138** [comment]
![image](https://user-images.githubusercontent.com/54617008/63833754-60f60200-c9a6-11e9-804c-bd6ab7d4aee5.png)
![image](https://user-images.githubusercontent.com/54617008/63833969-ccd86a80-c9a6-11e9-9032-cb566510d6f6.png)
