### ISSUE TITLE
公司历程的文字排版有点问题

### ISSUE THREAD

**Issue by michelle-sqa** [RanQiwu/website#3]
![image](https://user-images.githubusercontent.com/54617960/63837356-e92bd580-c9ad-11e9-9cb6-a7526aaf484d.png)

**Comment by RanQiwu** [comment]
自动换行，浏览尺寸改变应该就会消失。这个不是好控制。

**Comment by RanQiwu** [comment]
这问题无太多影响，所以我先关闭了。
